# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: "guest@aol.com", password: "password", name: "Guest Account", avatar: "http://i.imgur.com/RmKwLcc.jpg")
User.create(email: "CaptainPlanet@aol.com", password: "password", name: "CaptainPlanet", avatar: "http://i.imgur.com/RugrMDh.jpg")
User.create(email: "Kuzy@aol.com", password: "password", name: "Kuzy", avatar: "http://i.imgur.com/SjD71UR.jpg")
User.create(email: "BuffaloKing@aol.com", password: "password", name: "BuffaloKing", avatar: "http://i.imgur.com/3cEejvv.jpg")
User.create(email: "TheWizard@aol.com", password: "password", name: "TheWizard", avatar: "http://i.imgur.com/Ppg4hKd.jpg")
User.create(email: "Banana@aol.com", password: "password", name: "Banana", avatar: "http://i.imgur.com/6QY1qKJ.png")
User.create(email: "BlackWidow@aol.com", password: "password", name: "BlackWidow" , avatar: "http://i.imgur.com/OPFPydc.jpg")
User.create(email: "TheSaxMan@aol.com", password: "password", name: "TheSaxMan" , avatar: "http://i.imgur.com/2VV5ScK.jpg")
User.create(email: "Carissi@aol.com", password: "password", name: "Carissi" , avatar: "http://i.imgur.com/PkHG0XT.jpg")
User.create(email: "Chompy@aol.com", password: "password", name: "Chompy" , avatar: "http://i.imgur.com/tCPOkvF.png")
User.create(email: "WolfMan@aol.com", password: "password", name: "WolfMan", avatar: "http://i.imgur.com/BnklBdK.jpg")
User.create(email: "MasterMike@aol.com", password: "password", name: "MasterMike", avatar: "http://i.imgur.com/FGxiNmR.png")
User.create(email: "WhitePearl@aol.com", password: "password", name: "WhitePearl", avatar: "http://i.imgur.com/xxfQIdA.jpg")
User.create(email: "Kassanova@aol.com", password: "password", name: "Kassanova", avatar: "http://i.imgur.com/YoWjWt3.jpg")
User.create(email: "Scoobs@aol.com", password: "password", name: "Scoobs", avatar: "http://i.imgur.com/8PUIERR.jpg")
User.create(email: "Chefe@aol.com", password: "password", name: "Chefe", avatar: "http://i.imgur.com/raVKMVk.jpg")
User.create(email: "TheAdmiral@aol.com", password: "password", name: "TheAdmiral", avatar: "http://i.imgur.com/RmNLOx2.jpg")
User.create(email: "Jenga@aol.com", password: "password", name: "Jenga", avatar: "http://i.imgur.com/7Op03Z2.jpg")
User.create(email: "Banner@aol.com", password: "password", name: "Banner", avatar: "http://i.imgur.com/Z3uJhnG.jpg")
User.create(email: "BigKahuna@aol.com", password: "password", name: "BigKahuna", avatar: "http://i.imgur.com/ZrqNQ3P.jpg")
User.create(email: "BennyAndTheJets@aol.com", password: "password", name: "BennyAndTheJets", avatar: "http://i.imgur.com/HtQMrhr.jpg")
User.create(email: "TheDragon@aol.com", password: "password", name: "TheDragon", avatar: "http://i.imgur.com/dLCOEII.jpg")
User.create(email: "EZE@aol.com", password: "password", name: "EZE", avatar: "http://i.imgur.com/yOPVtz3.jpg")
User.create(email: "ActionHank@aol.com", password: "password", name: "ActionHank", avatar: "http://i.imgur.com/QhMKoJK.jpg")
User.create(email: "TheMatador@aol.com", password: "password", name: "TheMatador", avatar: "http://i.imgur.com/OZTDeXO.jpg")
User.create(email: "SubZero@aol.com", password: "password", name: "SubZero", avatar: "http://i.imgur.com/lFN5Ciw.jpg")
User.create(email: "WildCard@aol.com", password: "password", name: "WildCard", avatar: "http://i.imgur.com/B9p0dd3.jpg")
User.create(email: "Tasty@aol.com", password: "password", name: "Tasty", avatar: "http://i.imgur.com/No6NsgX.jpg")
User.create(email: "KarateKid@aol.com", password: "password", name: "KarateKid", avatar: "http://i.imgur.com/imnNKGN.jpg")
User.create(email: "Boomer@aol.com", password: "password", name: "Boomer", avatar: "http://i.imgur.com/ohAOqzl.jpg")
User.create(email: "TomTom@aol.com", password: "password", name: "TomTom", avatar: "http://i.imgur.com/h3mnKXP.jpg")
User.create(email: "BrickThorn@aol.com", password: "password", name: "BrickThorn", avatar: "http://i.imgur.com/hRjnZ5P.jpg")
User.create(email: "ChampMan@aol.com", password: "password", name: "ChampMan", avatar: "http://i.imgur.com/Tpe9ILP.jpg")
User.create(email: "FrogPrince@aol.com", password: "password", name: "FrogPrince", avatar: "http://i.imgur.com/BKH5nxY.jpg")